# Generated by Django 4.0.3 on 2022-03-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventsModel',
            new_name='EventModel',
        ),
    ]
