# Generated by Django 4.0.3 on 2022-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventmodel_user_who_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
