# Generated by Django 4.0.3 on 2022-03-29 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventmodel_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
