# Generated by Django 4.0.3 on 2022-04-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='available',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='user_who_attend',
        ),
    ]
