# Generated by Django 4.0.3 on 2022-04-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='product',
            new_name='event',
        ),
    ]
