# Generated by Django 4.0.3 on 2022-04-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventalbum_event_alter_imagemodel_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAlbum',
            new_name='EventAlbumModel',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.eventalbummodel'),
            preserve_default=False,
        ),
    ]
