# Generated by Django 4.0.3 on 2022-04-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_eventalbum_eventalbummodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventalbummodel'),
        ),
    ]
