# Generated by Django 4.0.3 on 2022-04-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_imagemodel_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventalbummodel'),
        ),
    ]
