# Generated by Django 4.0.3 on 2022-04-10 21:16

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventmodel_is_ready_alter_imagemodel_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=events.models.upload_to)),
            ],
        ),
    ]
