# Generated by Django 4.0.3 on 2022-04-04 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_book_user_who_got'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
