# Generated by Django 4.0.3 on 2022-04-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_imagebookmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='available',
        ),
    ]
