# Generated by Django 4.0.3 on 2022-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookmodel_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='date_of_giving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
