# Generated by Django 4.0.3 on 2022-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profilemodel_fee_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='school_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
