# Generated by Django 4.0.3 on 2022-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_profilemodel_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='password2',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
