# Generated by Django 4.0.3 on 2022-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
