# Generated by Django 4.0.3 on 2022-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_profilemodel_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='fee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
