# Generated by Django 4.0.3 on 2022-04-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_profilemodel_profile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='profile_foto',
            new_name='image',
        ),
    ]
