# Generated by Django 4.0.3 on 2022-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_profilemodel_grade_alter_profilemodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='grade',
            field=models.CharField(choices=[('Hazırlık Sınıfı', 'Hazırlık Sınıfı'), ('Birinci Sınıf', 'Birinci Sınıf'), ('İkinci Sınıf', 'İkinci Sınıf'), ('Üçüncü Sınıf', 'Üçüncü Sınıf'), ('Dördüncü Sınıf', 'Dördüncü Sınıf'), ('4+', '4+')], default='4+', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default=1345696748, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='school_number',
            field=models.CharField(default=12609, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
