# Generated by Django 4.0.3 on 2022-04-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(default='member', max_length=90),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='grade',
            field=models.CharField(blank=True, choices=[('0', 'Hazırlık Sınıfı'), ('1', 'Birinci Sınıf'), ('2', 'İkinci Sınıf'), ('3', 'Üçüncü Sınıf'), ('4', 'Dördüncü Sınıf'), ('5', '4+')], max_length=20, null=True),
        ),
    ]
