# Generated by Django 4.0.3 on 2022-03-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionModel',
        ),
        migrations.RenameModel(
            old_name='Survey',
            new_name='SurveyModel',
        ),
    ]
