# Generated by Django 4.0.3 on 2022-03-30 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_questionmodel_id_alter_surveymodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnswerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textAnswer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveymodel')),
            ],
        ),
    ]
