# Generated by Django 4.0.3 on 2022-03-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_booleananswermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleananswermodel',
            name='answer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
