# Generated by Django 4.0.3 on 2022-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_booleananswermodel_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveymodel',
            name='survey',
            field=models.ManyToManyField(to='survey.questionmodel'),
        ),
    ]
