# Generated by Django 4.0.3 on 2022-03-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_questionmodel_survey_surveymodel_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveymodel',
            old_name='survey',
            new_name='questions',
        ),
    ]
