# Generated by Django 4.0.3 on 2022-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_rename_survey_surveymodel_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='survey.questionmodel'),
        ),
    ]
