# Generated by Django 4.0.3 on 2022-03-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_surveymodel_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleananswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionmodel'),
        ),
        migrations.AlterField(
            model_name='textanswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionmodel'),
        ),
    ]
